# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_auto_20170425_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='decription',
            field=models.TextField(blank=True, help_text='Write about the food here', null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
