# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 06:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Homepage', '0003_auto_20170425_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_address', models.TextField()),
                ('lga', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'MALE'), (b'F', b'FEMALE')], max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[(b'SINGLE', b'SINGLE'), (b'MARRIED', b'MARRIED'), (b'OTHERS', b'OTHERS')], max_length=10, null=True)),
                ('phone', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(max_length=20)),
                ('user_wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Homepage.UserAccount')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='user_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Homepage.UserAccount'),
        ),
    ]
