# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_auto_20170504_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=20, null=True)),
                ('address1', models.CharField(max_length=20)),
                ('address2', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(max_length=20)),
                ('order_comment', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[(b'Monday', b'Monday'), (b'Tuesday', b'Tuesday'), (b'Wednesday', b'Wednesday'), (b'Thursday', b'Thursday'), (b'Friday', b'Friday'), (b'Saturday', b'Saturday'), (b'Sunday', b'Sunday')], max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='decription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='days_available',
            field=models.ManyToManyField(to='Homepage.WeekDay'),
        ),
    ]
