# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 12:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Homepage', '0005_auto_20170505_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.FileField(upload_to='media/')),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, help_text='Write about the food here', null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('days_available', models.ManyToManyField(to='Homepage.WeekDay')),
                ('food_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.FoodCategories')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.RemoveField(
            model_name='products',
            name='days_available',
        ),
        migrations.RemoveField(
            model_name='products',
            name='food_categories',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.Product'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
