# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_auto_20170505_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='days_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
