# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0007_auto_20170512_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='days_available',
            field=models.ManyToManyField(to='Homepage.WeekDay'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
