# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0011_auto_20170608_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Homepage.Orders'),
        ),
    ]
