# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0012_auto_20170608_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Homepage.Orders'),
        ),
    ]
