# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0013_auto_20170609_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Homepage.Orders'),
        ),
    ]
